let places = {
  "211 N. University Street" : "https://maps.illinoisstate.edu/locations/211/",
  "308 Kingsley Street" : "https://maps.illinoisstate.edu/locations/308-kingsley/",
  "604 North Adelaide Street" : "https://maps.illinoisstate.edu/locations/604N/",
  "608 S Main" : "https://maps.illinoisstate.edu/locations/old-facilities-planning/",
  "Academic Senate" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#academic-senate",
  "Accounting Office" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#accounting-office",
  "Accounting, Department of" : "https://maps.illinoisstate.edu/locations/business/academics/#accounting",
  "Adelaide Street Field" : "https://maps.illinoisstate.edu/locations/adelaide/",
  "Administration Building #1" : "https://maps.illinoisstate.edu/locations/adm/",
  "Administration Office" : "https://maps.illinoisstate.edu/locations/milner/academics/#mlb-admin",
  "Admissions, Office of" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-admissions",
  "Agriculture, Department of" : "https://maps.illinoisstate.edu/locations/ropp/academics/#department-of-agriculture",
  "Alumni Center" : "https://maps.illinoisstate.edu/locations/alumni/",
  "Alumni Center Parking Lot" : "https://maps.illinoisstate.edu/locations/parking-alumni-center/",
  "Alumni Engagement" : "https://maps.illinoisstate.edu/locations/alumni/services/#alumni-engagement",
  "Annual Giving Office" : "https://maps.illinoisstate.edu/locations/alumni/services/#annual-giving-office",
  "Applied Science and Technology, College of" : "https://maps.illinoisstate.edu/locations/turner/academics/#college-of-applied-science-and-technology",
  "Applied Social Research Unit" : "https://maps.illinoisstate.edu/locations/stevenson/services/#applied-social-research-unit",
  "Art, School of" : "https://maps.illinoisstate.edu/locations/visual/academics/#school-of-art",
  "Arts and Sciences, College of" : "https://maps.illinoisstate.edu/locations/stevenson/administrative/#college-of-arts-and-sciences",
  "Association of Residence Halls" : "https://maps.illinoisstate.edu/locations/vrooman-center/services/#association-of-residence-halls",
  "Athletic Development Office" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-development-office",
  "Athletic Director's Office" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-directors-office",
  "Athletic Eligibility and Compliance Office" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-eligibility-and-compliance-office",
  "Athletic Facility Scheduling" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-facility-scheduling",
  "Athletic Insurance" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-insurance",
  "Athletic Marketing Office" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-marketing-office",
  "Athletic and Redbird Arena Business Office" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#athletic-and-redbird-arena-business-office",
  "Atkin (Demolished)" : "https://maps.illinoisstate.edu/locations/atkin/",
  "Autism Spectrum Institute" : "https://maps.illinoisstate.edu/locations/college-place-uptown/academics/#autism-spectrum-institute",
  "Bill Waller Parking and Transportation Building" : "https://maps.illinoisstate.edu/locations/bill-waller/",
  "Biological Sciences, School of" : "https://maps.illinoisstate.edu/locations/julian/academics/#biological-sciences",
  "Birch Hall" : "https://maps.illinoisstate.edu/locations/cardinal/related-locations/#birch-hall",
  "Bone Student Center" : "https://maps.illinoisstate.edu/locations/bone/",
  "Bone Student Center Pay Lot" : "https://maps.illinoisstate.edu/locations/parking-bone/",
  "Bowling and Billiards Center" : "https://maps.illinoisstate.edu/locations/bowling/",
  "Box Office" : "https://maps.illinoisstate.edu/locations/performing/services/#cpa-box-office",
  "Braden Auditorium" : "https://maps.illinoisstate.edu/locations/braden/",
  "Braden Box Office" : "https://maps.illinoisstate.edu/locations/bone/services/#braden-box-office",
  "Brown Ballroom" : "https://maps.illinoisstate.edu/locations/brown/",
  "Budget Office" : "https://maps.illinoisstate.edu/locations/hovey/services/#budget-office",
  "Business, College of" : "https://maps.illinoisstate.edu/locations/business/academics/#college-business",
  "Business, College of - Academic Advisement" : "https://maps.illinoisstate.edu/locations/business/academics/#college-of-business-academic-advisement",
  "CEFCU Arena" : "https://maps.illinoisstate.edu/locations/redbird-arena/",
  "Campus Recreation" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/services/#campus-recreation",
  "Campus Religious Center" : "https://maps.illinoisstate.edu/locations/religious/",
  "Capen Auditorium" : "https://maps.illinoisstate.edu/locations/edwards/room-spaces/#capen-auditorium",
  "Cardinal Court" : "https://maps.illinoisstate.edu/locations/cardinal/",
  "Career Services" : "https://maps.illinoisstate.edu/locations/bone/services/#career-services",
  "Carter Harris Physical Plant" : "https://maps.illinoisstate.edu/locations/harris/",
  "Cashier's Office" : "https://maps.illinoisstate.edu/locations/student-accounts/services/#cashiers-office",
  "Cecilia J. Lauby Teacher Education Center" : "https://maps.illinoisstate.edu/locations/degarmo/academics/#cecilia-j-lauby-teacher-education-center",
  "Centennial East" : "https://maps.illinoisstate.edu/locations/centennial-east/",
  "Centennial West" : "https://maps.illinoisstate.edu/locations/centennial-west/",
  "Center for Adoption Studies" : "https://maps.illinoisstate.edu/locations/rachel-cooper/academics/#center-for-adoption-studies",
  "Center for Civic Engagement" : "https://maps.illinoisstate.edu/locations/civic-engagement/",
  "Center for Civic Engagement" : "https://maps.illinoisstate.edu/locations/civic-engagement/administrative/#civic-engagement",
  "Center for Integrated Professional Development" : "https://maps.illinoisstate.edu/locations/williams/academics/#center-integrated-professional-development",
  "Center for Mathematics, Science, and Technology" : "https://maps.illinoisstate.edu/locations/professional-annex/",
  "Center for Mathematics, Science, and Technology" : "https://maps.illinoisstate.edu/locations/professional-annex/academics/#center-for-mathematics-science-and-technology",
  "Center for Writing Research & Pedagogy" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#center-for-writing-research-and-pedagogy",
  "Center for the Performing Arts" : "https://maps.illinoisstate.edu/locations/performing/",
  "Center for the Study of Educational Policy" : "https://maps.illinoisstate.edu/locations/degarmo/services/#center-for-the-study-of-educational-policy",
  "Center for the Visual Arts" : "https://maps.illinoisstate.edu/locations/visual/",
  "Central Receiving Facility" : "https://maps.illinoisstate.edu/locations/property-control/services/#central-receiving",
  "Chemistry, Department of" : "https://maps.illinoisstate.edu/locations/julian/academics/#department-of-chemistry",
  "Child Care Center" : "https://maps.illinoisstate.edu/locations/turner/services/#child-care-center",
  "Civil Service Testing Center" : "https://maps.illinoisstate.edu/locations/308-kingsley/administrative/#cs-testing",
  "Classroom Building #1" : "https://maps.illinoisstate.edu/locations/606-ade/",
  "Classroom Building #2" : "https://maps.illinoisstate.edu/locations/210-main/",
  "Colby (Demolished)" : "https://maps.illinoisstate.edu/locations/colby/",
  "College Place Uptown" : "https://maps.illinoisstate.edu/locations/college-place-uptown/",
  "Communication Sciences and Disorders, Department of" : "https://maps.illinoisstate.edu/locations/fairchild/academics/#department-of-communication-sciences-and-disorders",
  "Communication, School of" : "https://maps.illinoisstate.edu/locations/fell/academics/#school-of-communication",
  "Communication, School of - Advisement Center" : "https://maps.illinoisstate.edu/locations/fell/academics/#school-of-communication-advisement-center",
  "Community Center" : "https://maps.illinoisstate.edu/locations/cardinal/related-locations/#community-center",
  "Comptroller, Office of the" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-the-comptroller",
  "Conference Services" : "https://maps.illinoisstate.edu/locations/alumni/services/#conference-services",
  "Cook Hall" : "https://maps.illinoisstate.edu/locations/cook/",
  "Creative Technologies" : "https://maps.illinoisstate.edu/locations/visual/academics/#creative-technologies",
  "Criminal Justice Sciences, Department of" : "https://maps.illinoisstate.edu/locations/schroeder/academics/#department-of-criminal-justice-sciences",
  "Cypress Hall" : "https://maps.illinoisstate.edu/locations/cardinal/related-locations/#cypress-hall",
  "Daily Vidette" : "https://maps.illinoisstate.edu/locations/DVB/",
  "Dance studio" : "https://maps.illinoisstate.edu/locations/dance/",
  "Dean of Students Office" : "https://maps.illinoisstate.edu/locations/student-services/services/#dean-of-students-office",
  "Degarmo Hall" : "https://maps.illinoisstate.edu/locations/degarmo/",
  "Developmental Math Lab " : "https://maps.illinoisstate.edu/locations/schroeder/academics/#developmental-math-lab",
  "Digital Innovation, Graphics, and Gaming Studio" : "https://maps.illinoisstate.edu/locations/julian/media/#diggs",
  "Division of Student Affairs" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#division-of-student-affairs",
  "Dogwood Hall" : "https://maps.illinoisstate.edu/locations/cardinal/related-locations/#dogwood-hall",
  "Donor and Information Services" : "https://maps.illinoisstate.edu/locations/alumni/services/#donor-and-information-services",
  "Dr. Jo Ann Rayfield Archives" : "https://maps.illinoisstate.edu/locations/milner/related-locations/#mlb-rayfield-archives",
  "Duffy Bass Field" : "https://maps.illinoisstate.edu/locations/duffy/",
  "Eckelmann-Taylor Speech and Hearing Clinic" : "https://maps.illinoisstate.edu/locations/rachel-cooper/services/#eckelmann-taylor-speech-and-hearing-clinic",
  "Economics, Department of" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#department-of-economics",
  "Education, College of" : "https://maps.illinoisstate.edu/locations/degarmo/academics/#college-of-education",
  "Educational Administration and Foundations, Department of" : "https://maps.illinoisstate.edu/locations/degarmo/academics/#department-of-educational-administration-and-foundations",
  "Edwards Hall" : "https://maps.illinoisstate.edu/locations/edwards/",
  "English Language Institute" : "https://maps.illinoisstate.edu/locations/hudelson/other/#english-language-institute",
  "English, Department of" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#department-of-english",
  "Enrollment Management and Academic Services, Office of" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-enrollment-management-and-academic-services",
  "Enterprise Data and Analytics" : "https://maps.illinoisstate.edu/locations/professional/administrative/#enterprise-data-analytics",
  "Environmental Health and Safety" : "https://maps.illinoisstate.edu/locations/adm/services/#environmental-health-and-safety",
  "Equal Opportunity and Access, Office of" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-equal-opportunity-and-access",
  "Event Management, Dining, and Hospitality" : "https://maps.illinoisstate.edu/locations/student-services/services/#events-dining-hospitality",
  "Evergreen Hall" : "https://maps.illinoisstate.edu/locations/cardinal/related-locations/#evergreen-hall",
  "Ewing Cultural Center" : "https://maps.illinoisstate.edu/locations/ewing/",
  "Exercise Physiology Laboratory" : "https://maps.illinoisstate.edu/locations/horton/room-spaces/#excercise-physiology-laboratory",
  "Eyestone School Museum" : "https://maps.illinoisstate.edu/locations/eyestone/",
  "Facilities Administration" : "https://maps.illinoisstate.edu/locations/adm/services/#facilities-administration",
  "Facilities Planning and Construction" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#facilities-planning-and-construction",
  "Fairchild Hall" : "https://maps.illinoisstate.edu/locations/fairchild/",
  "Family and Consumer Sciences, Department of" : "https://maps.illinoisstate.edu/locations/turner/academics/#department-of-family-and-consumer-sciences",
  "Feeney (Demolished)" : "https://maps.illinoisstate.edu/locations/feeney/",
  "Fell Arboretum" : "https://maps.illinoisstate.edu/locations/quad/room-spaces/#fell-arboretum",
  "Fell Hall" : "https://maps.illinoisstate.edu/locations/fell/",
  "Felmley Hall of Science" : "https://maps.illinoisstate.edu/locations/felmley/",
  "Felmley Hall of Science Annex" : "https://maps.illinoisstate.edu/locations/felmley-annex/",
  "Felmley Hall of Science Annex Greenhouse" : "https://maps.illinoisstate.edu/locations/felmley-greenhouse/",
  "Finance, Insurance, and Law, Department of" : "https://maps.illinoisstate.edu/locations/business/academics/#department-of-finance-insurance-and-law",
  "Financial Aid Office" : "https://maps.illinoisstate.edu/locations/hovey/services/#financial-aid-office",
  "Fine Arts, College of" : "https://maps.illinoisstate.edu/locations/visual/academics/#college-of-fine-arts",
  "Fir Hall" : "https://maps.illinoisstate.edu/locations/cardinal/related-locations/#fir-hall",
  "Foundation Office" : "https://maps.illinoisstate.edu/locations/alumni/services/#foundation-office",
  "Gamma Phi Circus" : "https://maps.illinoisstate.edu/locations/horton/academics/#gamma-phi-circus",
  "General Counsel, Office of" : "https://maps.illinoisstate.edu/locations/hovey/services/#office-of-general-counsel",
  "Geography, Geology, and the Environment, Department of" : "https://maps.illinoisstate.edu/locations/felmley/academics/#department-of-geography-geology",
  "George R. and Martha Means Center for Entrepreneurial Studies" : "https://maps.illinoisstate.edu/locations/business/services/#center-entrepreneurial-studies",
  "Golf Course Chemical Rinsate" : "https://maps.illinoisstate.edu/locations/rinsate/",
  "Graduate School" : "https://maps.illinoisstate.edu/locations/hovey/academics/#graduate-school",
  "Grants Accounting Office" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#grants-office",
  "Grapevine Publication" : "https://maps.illinoisstate.edu/locations/degarmo/services/#grapevine-publication",
  "Gregory Street Property (GSPF)" : "https://maps.illinoisstate.edu/locations/gregory/",
  "Gregory Street Tennis Courts" : "https://maps.illinoisstate.edu/locations/gregory-tennis/",
  "Grounds Equipment Building" : "https://maps.illinoisstate.edu/locations/grounds/",
  "Hamilton (Demolished)" : "https://maps.illinoisstate.edu/locations/hamilton/",
  "Hancock Stadium" : "https://maps.illinoisstate.edu/locations/hancock/",
  "Hancock Stadium Club" : "https://maps.illinoisstate.edu/locations/hancock/room-spaces/#hancock-club",
  "Hayden Auditorium" : "https://maps.illinoisstate.edu/locations/hayden/",
  "Haynie Hall" : "https://maps.illinoisstate.edu/locations/haynie/",
  "Health Promotion and Wellness" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/services/#heath-promotion-and-wellness",
  "Health Sciences, Department of" : "https://maps.illinoisstate.edu/locations/felmley/academics/#department-of-health-sciences",
  "Heating Plant" : "https://maps.illinoisstate.edu/locations/heating/",
  "Hewett Hall" : "https://maps.illinoisstate.edu/locations/hewett/",
  "History, Department of" : "https://maps.illinoisstate.edu/locations/schroeder/academics/#department-of-history",
  "Honors Program" : "https://maps.illinoisstate.edu/locations/professional/academics/#honors-program",
  "Honors Program Building" : "https://maps.illinoisstate.edu/locations/professional/",
  "Horticulture Center" : "https://maps.illinoisstate.edu/locations/horticulture/",
  "Horton Field House" : "https://maps.illinoisstate.edu/locations/horton/",
  "Horton Pool" : "https://maps.illinoisstate.edu/locations/horton/room-spaces/#horton-pool",
  "Hovey Hall" : "https://maps.illinoisstate.edu/locations/hovey/",
  "Hudelson Building" : "https://maps.illinoisstate.edu/locations/hudelson/",
  "Human Resources" : "https://maps.illinoisstate.edu/locations/smith/services/#human-resources",
  "ISU Annuitants Association" : "https://maps.illinoisstate.edu/locations/alumni/services/#annuitants-association",
  "ISU Credit Union" : "https://maps.illinoisstate.edu/locations/credit/",
  "ISU Credit Union" : "https://maps.illinoisstate.edu/locations/bone/other/#credit-bone",
  "Illinois Regional Archives Repository (IRAD)" : "https://maps.illinoisstate.edu/locations/milner/related-locations/#mlb-collections-irad",
  "Illinois State University Bands" : "https://maps.illinoisstate.edu/locations/centennial-east/administrative/#illinois-state-university-bands",
  "Illinois State University Catering" : "https://maps.illinoisstate.edu/locations/bone/services/#taste-of-excellence-catering",
  "In Exchange" : "https://maps.illinoisstate.edu/locations/inexchange/",
  "Information Technology, School of" : "https://maps.illinoisstate.edu/locations/old-union/academics/#information-technology",
  "Institute for Geospatial Analysis & Mapping (GEOMAP)" : "https://maps.illinoisstate.edu/locations/felmley/academics/#institute-for-geospatial-analysis-and-mapping",
  "Institute for Regulatory Policy Studies" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#institute-for-regulatory-policy-studies",
  "Interdisciplinary Programs" : "https://maps.illinoisstate.edu/locations/williams/academics/#interdisciplinary-programs",
  "Internal Auditing, Office of" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-internal-auditing",
  "International House" : "https://maps.illinoisstate.edu/locations/vrooman-center/services/#international-house",
  "International Studies and Programs, Office of" : "https://maps.illinoisstate.edu/locations/fell/academics/#office-of-international-studies-and-programs",
  "John Green Food Service Building" : "https://maps.illinoisstate.edu/locations/green/",
  "Julian Hall" : "https://maps.illinoisstate.edu/locations/julian/",
  "Karin L. Bone Athletic Study Center" : "https://maps.illinoisstate.edu/locations/211/academics/#karin",
  "Katie School of Insurance and Financial Services" : "https://maps.illinoisstate.edu/locations/business/academics/#katie-school-of-insurance-and-financial-services",
  "Kaufman Football Building" : "https://maps.illinoisstate.edu/locations/kaufman/",
  "Kemp Recital Hall" : "https://maps.illinoisstate.edu/locations/kemp-loc/",
  "Kinesiology and Recreation, School of" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/academics/#school-of-kinesiology-and-recreation",
  "Kinesiology and Recreation, School of - Academic Advisement" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/academics/#school-of-kinesiology-and-recreation-academic-advisement",
  "Languages, Literatures, and Cultures, Department of" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#department-of-languages-literatures-and-cultures",
  "Leadership Education and Development" : "https://maps.illinoisstate.edu/locations/bone/services/#lead",
  "Learning Spaces & Audio/Visual Technologies" : "https://maps.illinoisstate.edu/locations/smith/services/#learning-spaces-and-audio-visual-technologies",
  "Linkins Dining Center" : "https://maps.illinoisstate.edu/locations/linkins/",
  "Mail Service Center" : "https://maps.illinoisstate.edu/locations/smith/services/#mail-service-center",
  "Management, Department of" : "https://maps.illinoisstate.edu/locations/business/academics/#department-of-management",
  "Manchester Hall" : "https://maps.illinoisstate.edu/locations/manchester/",
  "Marian Kneer Softball Stadium" : "https://maps.illinoisstate.edu/locations/softball/",
  "Marketing, Department of" : "https://maps.illinoisstate.edu/locations/business/academics/#department-of-marketing",
  "Master of Business Administration Program" : "https://maps.illinoisstate.edu/locations/business/academics/#master-of-business-administration-program",
  "Mathematics, Department of" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#department-of-mathematics",
  "McAlister's Deli" : "https://maps.illinoisstate.edu/locations/bone/dining-options/#mcalisters-deli",
  "Media Relations" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#media-relations",
  "Mennonite College of Nursing" : "https://maps.illinoisstate.edu/locations/edwards/academics/#mennonite-college-of-nursing",
  "Military Science, Department of" : "https://maps.illinoisstate.edu/locations/211/other/#army-rotc",
  "Milner Library" : "https://maps.illinoisstate.edu/locations/milner/",
  "Milner Library uLab" : "https://maps.illinoisstate.edu/locations/milner/academics/#milner-library-ulab",
  "Moulton Hall" : "https://maps.illinoisstate.edu/locations/moulton/",
  "Mounier Golf Training Center" : "https://maps.illinoisstate.edu/locations/weibring/related-locations/#mounier-golf",
  "Multicultural Center" : "https://maps.illinoisstate.edu/locations/mcc/",
  "Music, School of" : "https://maps.illinoisstate.edu/locations/centennial-east/academics/#school-of-music",
  "National Board Resource Center" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#national-board-resource-center",
  "Nelson Smith Building" : "https://maps.illinoisstate.edu/locations/smith/",
  "Nite Ride Building" : "https://maps.illinoisstate.edu/locations/nite/",
  "Normal Editions" : "https://maps.illinoisstate.edu/locations/visual/services/#normal-editions",
  "Normal Theater" : "https://maps.illinoisstate.edu/locations/normal-theater/",
  "North Gym" : "https://maps.illinoisstate.edu/locations/horton/room-spaces/#north-gym",
  "Nursing Simulation Laboratory" : "https://maps.illinoisstate.edu/locations/simulation/",
  "Office of Energy Management" : "https://maps.illinoisstate.edu/locations/green/administrative/#energy",
  "Office of Residential Life" : "https://maps.illinoisstate.edu/locations/residential-life/",
  "Office of Sustainability" : "https://maps.illinoisstate.edu/locations/sustainability/",
  "Office of Sustainability" : "https://maps.illinoisstate.edu/locations/sustainability/services/#office-of-sustainability",
  "Old Union Building" : "https://maps.illinoisstate.edu/locations/old-union/",
  "Opscan Evaluation" : "https://maps.illinoisstate.edu/locations/williams/services/#opscan-evaluation",
  "Parking and Transportation, Office of" : "https://maps.illinoisstate.edu/locations/bill-waller/services/#office-of-parking-and-transportation",
  "Payroll Office" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#payroll-office",
  "People's Park" : "https://maps.illinoisstate.edu/locations/peoples-park/",
  "Philosophy, Department of" : "https://maps.illinoisstate.edu/locations/stevenson/academics/#department-of-philosophy",
  "Physical Plant Greenhouse" : "https://maps.illinoisstate.edu/locations/physical-plant/",
  "Physics, Department of" : "https://maps.illinoisstate.edu/locations/moulton/academics/#department-of-physics",
  "Planetarium" : "https://maps.illinoisstate.edu/locations/planetarium/",
  "Planning, Research, & Policy Analysis" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#planning-research-and-policy-analysis",
  "Politics and Government, Department of" : "https://maps.illinoisstate.edu/locations/schroeder/academics/#department-of-politics-and-government",
  "Practice Field" : "https://maps.illinoisstate.edu/locations/practice/",
  "Prefab Control Building" : "https://maps.illinoisstate.edu/locations/prefab/",
  "President, Office of the" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-the-president",
  "Printing Services" : "https://maps.illinoisstate.edu/locations/smith/services/#printing-services",
  "Printing Services (BSC)" : "https://maps.illinoisstate.edu/locations/bone/services/#printing-bone",
  "Professional Sales Institute" : "https://maps.illinoisstate.edu/locations/business/services/#professional-sales-institute",
  "Property Control Building" : "https://maps.illinoisstate.edu/locations/property-control/",
  "Provost, Office of the" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#office-of-the-provost",
  "Psychology, Department of" : "https://maps.illinoisstate.edu/locations/degarmo/academics/#psychology-department",
  "Purchasing Office" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#purchasing-office",
  "Qdoba" : "https://maps.illinoisstate.edu/locations/bone/dining-options/#qdoba-bone",
  "Quad" : "https://maps.illinoisstate.edu/locations/quad/",
  "Rachel Cooper" : "https://maps.illinoisstate.edu/locations/rachel-cooper/",
  "Rappelling Tower and Low Ropes Course" : "https://maps.illinoisstate.edu/locations/rappelling-tower/",
  "Redbird Adventure Center" : "https://maps.illinoisstate.edu/locations/adventure-center/",
  "Redbird Card Office" : "https://maps.illinoisstate.edu/locations/bone/services/#redbird-card-office",
  "Redbird Plaza" : "https://maps.illinoisstate.edu/locations/redbird-plaza/",
  "Redbird Spirit Shop" : "https://maps.illinoisstate.edu/locations/bone/services/#redbird-spirit-shop",
  "Redbird Tent Zone" : "https://maps.illinoisstate.edu/locations/tent-zone/",
  "Redbird Track & Field Complex" : "https://maps.illinoisstate.edu/locations/track/",
  "Reference Desk" : "https://maps.illinoisstate.edu/locations/milner/academics/#milner-library-desk",
  "Registrar" : "https://maps.illinoisstate.edu/locations/moulton/services/#office-of-the-university-registrar",
  "Research & Sponsored Programs" : "https://maps.illinoisstate.edu/locations/college-place-uptown/academics/#research-and-sponsored-programs",
  "Research Ethics and Compliance, Office of" : "https://maps.illinoisstate.edu/locations/college-place-uptown/academics/#research-ethics-and-compliance",
  "Risk Management" : "https://maps.illinoisstate.edu/locations/risk-management/",
  "Ropp Agriculture Building" : "https://maps.illinoisstate.edu/locations/ropp/",
  "School Street Parking Garage" : "https://maps.illinoisstate.edu/locations/parking-school-street-garage/",
  "School of Theatre and Dance" : "https://maps.illinoisstate.edu/locations/centennial-west/academics/#school-theatre-dance",
  "Schroeder Hall" : "https://maps.illinoisstate.edu/locations/schroeder/",
  "Schroeder Hall Annex" : "https://maps.illinoisstate.edu/locations/schroeder-annex/",
  "Science Laboratory Building" : "https://maps.illinoisstate.edu/locations/science-laboratory/",
  "Science Laboratory Building Greenhouses" : "https://maps.illinoisstate.edu/locations/science-laboratory-greenhouses/",
  "Shelbourne Apartments" : "https://maps.illinoisstate.edu/locations/shelbourne-apartments/",
  "Social Work, School of" : "https://maps.illinoisstate.edu/locations/rachel-cooper/academics/#school-of-social-work",
  "Sociology and Anthropology, Department of" : "https://maps.illinoisstate.edu/locations/schroeder/academics/#department-of-sociology-and-anthropology",
  "Sorority and Fraternity Life" : "https://maps.illinoisstate.edu/locations/bone/services/#sfl",
  "South Campus Power Plant" : "https://maps.illinoisstate.edu/locations/power-plant/",
  "South University Street Garage" : "https://maps.illinoisstate.edu/locations/parking-south-university-garage/",
  "Southeast Chilled Water Plant" : "https://maps.illinoisstate.edu/locations/water-plant/",
  "Special Collections" : "https://maps.illinoisstate.edu/locations/milner/academics/#special-collections",
  "Special Education, Department of" : "https://maps.illinoisstate.edu/locations/degarmo/academics/#department-of-special-education",
  "Sports Information Office" : "https://maps.illinoisstate.edu/locations/horton/other/#sports-information-office",
  "Sports Medicine and Rehabilitation Therapy Clinic" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/services/#sports-medicine-and-rehabilitation-therapy-clinic",
  "Starbucks" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/dining-options/#starbucks",
  "Starbucks" : "https://maps.illinoisstate.edu/locations/bone/dining-options/#starbucks-bone",
  "State Farm Hall of Business" : "https://maps.illinoisstate.edu/locations/business/",
  "Stevenson Center for Community and Economic Development" : "https://maps.illinoisstate.edu/locations/stevenson/services/#stevenson-center-for-community-and-economic-development",
  "Stevenson Hall" : "https://maps.illinoisstate.edu/locations/stevenson/",
  "Stroud Auditorium" : "https://maps.illinoisstate.edu/locations/uhigh/room-spaces/#stroud-auditorium",
  "Student Access and Accommodation Services" : "https://maps.illinoisstate.edu/locations/fell/services/#student-access",
  "Student Accounts Building" : "https://maps.illinoisstate.edu/locations/student-accounts/",
  "Student Accounts Office" : "https://maps.illinoisstate.edu/locations/student-accounts/services/#student-accounts",
  "Student Activities" : "https://maps.illinoisstate.edu/locations/bone/services/#student-activities",
  "Student Affairs Information Technology" : "https://maps.illinoisstate.edu/locations/student-services/services/#student-affairs-information-technology",
  "Student Conduct and Community Responsibilities" : "https://maps.illinoisstate.edu/locations/student-services/services/#student-conduct-conflict",
  "Student Counseling Services" : "https://maps.illinoisstate.edu/locations/student-services/services/#student-counseling-services",
  "Student Fitness Center and McCormick Hall" : "https://maps.illinoisstate.edu/locations/fitness-mccormick/",
  "Student Government Assocation" : "https://maps.illinoisstate.edu/locations/student-services/services/#student-government-association",
  "Student Health Services" : "https://maps.illinoisstate.edu/locations/student-services/services/#student-health-services",
  "Student Insurance Office" : "https://maps.illinoisstate.edu/locations/student-services/services/#student-insurance-office",
  "Student Involvement Center" : "https://maps.illinoisstate.edu/locations/bone/services/#sic",
  "Student Services Building" : "https://maps.illinoisstate.edu/locations/student-services/",
  "Students' Attorney" : "https://maps.illinoisstate.edu/locations/student-services/services/#students-attorney",
  "Studio TEaCH" : "https://maps.illinoisstate.edu/locations/degarmo/room-spaces/#studio-teach",
  "Study Abroad" : "https://maps.illinoisstate.edu/locations/fell/academics/#study-abroad",
  "Study Spaces" : "https://maps.illinoisstate.edu/locations/milner/academics/#mlb-study-spaces",
  "TRiO/Student Support Services" : "https://maps.illinoisstate.edu/locations/fell/services/#trio-student-support-services",
  "TV-10 News" : "https://maps.illinoisstate.edu/locations/fell/media/#tv-10-news",
  "Teaching and Learning, School of" : "https://maps.illinoisstate.edu/locations/degarmo/academics/#school-of-teaching-and-learning",
  "TechZone" : "https://maps.illinoisstate.edu/locations/bone/services/#tech-zone",
  "Technology Solutions" : "https://maps.illinoisstate.edu/locations/julian/services/#tech-solutions",
  "Technology Support Center" : "https://maps.illinoisstate.edu/locations/julian/services/#technology-support-center",
  "Technology, Department of" : "https://maps.illinoisstate.edu/locations/turner/academics/#department-of-technology",
  "Testing Services" : "https://maps.illinoisstate.edu/locations/moulton/services/#testing-services",
  "The Business Bistro" : "https://maps.illinoisstate.edu/locations/business/dining-options/#business-bistro",
  "The English Department's Publications Unit" : "https://maps.illinoisstate.edu/locations/williams-annex/academics/#publications-unit",
  "The Landing" : "https://maps.illinoisstate.edu/locations/bone/dining-options/#landing",
  "The Library of Congress Teaching with Primary Sources Midwest Region" : "https://maps.illinoisstate.edu/locations/milner/academics/#mlb-libcongress",
  "Thomas Eimermann Pre-Law Advisement Center" : "https://maps.illinoisstate.edu/locations/schroeder/services/#thomas-eimermann-pre-law-advisement-center",
  "Thomas Metcalf School" : "https://maps.illinoisstate.edu/locations/thomas-metcalf-school/",
  "Ticket Office" : "https://maps.illinoisstate.edu/locations/redbird-arena/administrative/#ticket-office",
  "Timbers Grille" : "https://maps.illinoisstate.edu/locations/bone/dining-options/#timbers-grille",
  "Title IX" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#title-ix",
  "Transpace" : "https://maps.illinoisstate.edu/locations/visual/services/#transpace",
  "Travel Office" : "https://maps.illinoisstate.edu/locations/college-place-uptown/services/#travel-office",
  "Turner Hall" : "https://maps.illinoisstate.edu/locations/turner/",
  "University Advancement" : "https://maps.illinoisstate.edu/locations/alumni/administrative/#university-advancement",
  "University Archives" : "https://maps.illinoisstate.edu/locations/archives/",
  "University Assessment Services" : "https://maps.illinoisstate.edu/locations/308-kingsley/services/#university-assessment-services",
  "University College" : "https://maps.illinoisstate.edu/locations/fell/services/#university-college",
  "University College Academic Advisement" : "https://maps.illinoisstate.edu/locations/fell/services/#university-college-academic-advisement",
  "University Farm" : "https://maps.illinoisstate.edu/locations/farm/",
  "University Galleries" : "https://maps.illinoisstate.edu/locations/university-gallery/",
  "University High School" : "https://maps.illinoisstate.edu/locations/uhigh/",
  "University High School Soccer Field" : "https://maps.illinoisstate.edu/locations/uhigh-soccer/",
  "University High School Tennis Courts" : "https://maps.illinoisstate.edu/locations/uhigh-tennis/",
  "University Housing Services" : "https://maps.illinoisstate.edu/locations/residential-life/services/#housing",
  "University Marketing" : "https://maps.illinoisstate.edu/locations/alumni/services/#university-marketing",
  "University Police" : "https://maps.illinoisstate.edu/locations/smith/services/#police",
  "University Residence" : "https://maps.illinoisstate.edu/locations/president/",
  "Veterans and Military Services" : "https://maps.illinoisstate.edu/locations/moulton/services/#veterans-and-military-services",
  "Vice President for Finance and Planning, Office of" : "https://maps.illinoisstate.edu/locations/hovey/administrative/#vice-president-for-finance-and-planning",
  "Vidette" : "https://maps.illinoisstate.edu/locations/DVB/administrative/#vidette-office",
  "Visor Center" : "https://maps.illinoisstate.edu/locations/vrooman-center/services/#julia-n-visor-academic-center",
  "Vitro Center" : "https://maps.illinoisstate.edu/locations/vitro/",
  "Vrooman Center" : "https://maps.illinoisstate.edu/locations/vrooman-center/",
  "WGLT Radio" : "https://maps.illinoisstate.edu/locations/DVB/media/#wglt-radio",
  "WZND Radio" : "https://maps.illinoisstate.edu/locations/fell/media/#wznd-radio",
  "Watterson Dining Commons" : "https://maps.illinoisstate.edu/locations/watterson-dining/",
  "Watterson Towers" : "https://maps.illinoisstate.edu/locations/watterson/",
  "Web and Interactive Communications" : "https://maps.illinoisstate.edu/locations/old-union/services/#web-interactive-communications",
  "Weibring Golf Club" : "https://maps.illinoisstate.edu/locations/weibring/",
  "Welcome Desk" : "https://maps.illinoisstate.edu/locations/bone/services/#welcome-desk",
  "Westhoff Theatre" : "https://maps.illinoisstate.edu/locations/westhoff/",
  "Whitten (Demolished)" : "https://maps.illinoisstate.edu/locations/whitten/",
  "Wilkins Hall" : "https://maps.illinoisstate.edu/locations/wilkins/",
  "Williams Hall" : "https://maps.illinoisstate.edu/locations/williams/",
  "Williams Hall Annex" : "https://maps.illinoisstate.edu/locations/williams-annex/",
  "Women's Mentoring Network" : "https://maps.illinoisstate.edu/locations/fell/services/#womens-mentoring-network",
  "Women's, Gender, and Sexuality Studies Program" : "https://maps.illinoisstate.edu/locations/rachel-cooper/academics/#womens-and-gender-studies-program",
  "Wonsook Kim College of Fine Arts IT" : "https://maps.illinoisstate.edu/locations/visual/services/#college-of-fine-arts-it",
  "Wright Hall" : "https://maps.illinoisstate.edu/locations/wright/"
}